/**
 * Premium feature gating.
 *
 * All features are FREE for now. When you're ready to enable the paywall:
 * 1. Set PREMIUM_ENABLED = true
 * 2. Wire up Stripe (see PaywallScreen.tsx)
 * 3. Update PREMIUM_FEATURES to reflect what's gated
 *
 * This module is the single source of truth — never scatter is_premium checks
 * through the app. Always call isPremium(profile) or useFeature(feature, profile).
 */

import { Profile } from '@nouri/shared/types';

export const PREMIUM_ENABLED = false; // Flip to true when ready

export type PremiumFeature =
  | 'ai_meal_plan'        // AI-generated weekly meal plans
  | 'ai_diary_analysis'   // Weekly AI diary feedback
  | 'pantry_suggestions'  // Pantry → recipe AI
  | 'coach_marketplace'   // Access to coach marketplace
  | 'advanced_analytics'  // Body comp trends, micronutrients
  | 'cgm_integration'     // Dexcom / Libre glucose sync
  | 'wearable_sync'       // Fitbit, Garmin, Whoop
  | 'unlimited_recipes'   // >10 saved recipes
  | 'export_data';        // PDF / CSV diary export

// Describe the free tier limits (when PREMIUM_ENABLED = true)
export const FREE_LIMITS: Partial<Record<PremiumFeature, { limit: number; unit: string }>> = {
  unlimited_recipes: { limit: 10, unit: 'saved recipes' },
};

/**
 * Returns true if the user has access to a feature.
 * When PREMIUM_ENABLED is false, everyone has access to everything.
 */
export function canUseFeature(feature: PremiumFeature, profile: Profile | null): boolean {
  if (!PREMIUM_ENABLED) return true;
  if (profile?.is_premium) return true;

  // Features that are always free
  const alwaysFree: PremiumFeature[] = [];
  if (alwaysFree.includes(feature)) return true;

  return false;
}

/**
 * Returns a human-readable description for each premium feature (shown on paywall).
 */
export const PREMIUM_FEATURE_DESCRIPTIONS: Record<PremiumFeature, { title: string; icon: string; desc: string }> = {
  ai_meal_plan: {
    title: 'AI Meal Plans',
    icon: 'sparkles',
    desc: 'Personalized 7-day meal plans generated by AI based on your goals and preferences.',
  },
  ai_diary_analysis: {
    title: 'Weekly AI Feedback',
    icon: 'bar-chart',
    desc: 'Get a detailed weekly analysis of your diary with specific improvement suggestions.',
  },
  pantry_suggestions: {
    title: 'Pantry-to-Plate AI',
    icon: 'restaurant',
    desc: "Tell us what's in your fridge and get instant recipe ideas tailored to your macros.",
  },
  coach_marketplace: {
    title: 'Coach Marketplace',
    icon: 'people',
    desc: 'Work 1-on-1 with certified dietitians and nutrition coaches.',
  },
  advanced_analytics: {
    title: 'Advanced Analytics',
    icon: 'trending-up',
    desc: 'Body composition trends, micronutrient breakdown, and long-term progress charts.',
  },
  cgm_integration: {
    title: 'CGM Integration',
    icon: 'pulse',
    desc: 'Sync glucose data from Dexcom or Libre to see how food affects your blood sugar.',
  },
  wearable_sync: {
    title: 'Wearable Sync',
    icon: 'watch',
    desc: 'Connect Fitbit, Garmin, Whoop, or Apple Watch for automatic calorie burn data.',
  },
  unlimited_recipes: {
    title: 'Unlimited Recipe Saves',
    icon: 'bookmark',
    desc: 'Save as many recipes as you want. Free tier is limited to 10.',
  },
  export_data: {
    title: 'Export Your Data',
    icon: 'download',
    desc: 'Download your food diary, measurements, and progress as PDF or CSV.',
  },
};

export const PREMIUM_PLANS = [
  {
    id: 'monthly',
    label: 'Monthly',
    price: 9.99,
    period: '/month',
    stripePriceId: process.env.EXPO_PUBLIC_STRIPE_MONTHLY_PRICE_ID,
    badge: null,
  },
  {
    id: 'annual',
    label: 'Annual',
    price: 4.99,
    period: '/month',
    originalPrice: 9.99,
    stripePriceId: process.env.EXPO_PUBLIC_STRIPE_ANNUAL_PRICE_ID,
    badge: 'Save 50%',
  },
];
